require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MotoristaosController do

  # This should return the minimal set of attributes required to create a valid
  # Motoristao. As you add validations to Motoristao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MotoristaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all motoristaos as @motoristaos" do
      motoristao = Motoristao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:motoristaos).should eq([motoristao])
    end
  end

  describe "GET show" do
    it "assigns the requested motoristao as @motoristao" do
      motoristao = Motoristao.create! valid_attributes
      get :show, {:id => motoristao.to_param}, valid_session
      assigns(:motoristao).should eq(motoristao)
    end
  end

  describe "GET new" do
    it "assigns a new motoristao as @motoristao" do
      get :new, {}, valid_session
      assigns(:motoristao).should be_a_new(Motoristao)
    end
  end

  describe "GET edit" do
    it "assigns the requested motoristao as @motoristao" do
      motoristao = Motoristao.create! valid_attributes
      get :edit, {:id => motoristao.to_param}, valid_session
      assigns(:motoristao).should eq(motoristao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Motoristao" do
        expect {
          post :create, {:motoristao => valid_attributes}, valid_session
        }.to change(Motoristao, :count).by(1)
      end

      it "assigns a newly created motoristao as @motoristao" do
        post :create, {:motoristao => valid_attributes}, valid_session
        assigns(:motoristao).should be_a(Motoristao)
        assigns(:motoristao).should be_persisted
      end

      it "redirects to the created motoristao" do
        post :create, {:motoristao => valid_attributes}, valid_session
        response.should redirect_to(Motoristao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved motoristao as @motoristao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Motoristao.any_instance.stub(:save).and_return(false)
        post :create, {:motoristao => {}}, valid_session
        assigns(:motoristao).should be_a_new(Motoristao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Motoristao.any_instance.stub(:save).and_return(false)
        post :create, {:motoristao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested motoristao" do
        motoristao = Motoristao.create! valid_attributes
        # Assuming there are no other motoristaos in the database, this
        # specifies that the Motoristao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Motoristao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => motoristao.to_param, :motoristao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested motoristao as @motoristao" do
        motoristao = Motoristao.create! valid_attributes
        put :update, {:id => motoristao.to_param, :motoristao => valid_attributes}, valid_session
        assigns(:motoristao).should eq(motoristao)
      end

      it "redirects to the motoristao" do
        motoristao = Motoristao.create! valid_attributes
        put :update, {:id => motoristao.to_param, :motoristao => valid_attributes}, valid_session
        response.should redirect_to(motoristao)
      end
    end

    describe "with invalid params" do
      it "assigns the motoristao as @motoristao" do
        motoristao = Motoristao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Motoristao.any_instance.stub(:save).and_return(false)
        put :update, {:id => motoristao.to_param, :motoristao => {}}, valid_session
        assigns(:motoristao).should eq(motoristao)
      end

      it "re-renders the 'edit' template" do
        motoristao = Motoristao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Motoristao.any_instance.stub(:save).and_return(false)
        put :update, {:id => motoristao.to_param, :motoristao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested motoristao" do
      motoristao = Motoristao.create! valid_attributes
      expect {
        delete :destroy, {:id => motoristao.to_param}, valid_session
      }.to change(Motoristao, :count).by(-1)
    end

    it "redirects to the motoristaos list" do
      motoristao = Motoristao.create! valid_attributes
      delete :destroy, {:id => motoristao.to_param}, valid_session
      response.should redirect_to(motoristaos_url)
    end
  end

end
