require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrdemservicosController do

  # This should return the minimal set of attributes required to create a valid
  # Ordemservico. As you add validations to Ordemservico, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdemservicosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ordemservicos as @ordemservicos" do
      ordemservico = Ordemservico.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ordemservicos).should eq([ordemservico])
    end
  end

  describe "GET show" do
    it "assigns the requested ordemservico as @ordemservico" do
      ordemservico = Ordemservico.create! valid_attributes
      get :show, {:id => ordemservico.to_param}, valid_session
      assigns(:ordemservico).should eq(ordemservico)
    end
  end

  describe "GET new" do
    it "assigns a new ordemservico as @ordemservico" do
      get :new, {}, valid_session
      assigns(:ordemservico).should be_a_new(Ordemservico)
    end
  end

  describe "GET edit" do
    it "assigns the requested ordemservico as @ordemservico" do
      ordemservico = Ordemservico.create! valid_attributes
      get :edit, {:id => ordemservico.to_param}, valid_session
      assigns(:ordemservico).should eq(ordemservico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ordemservico" do
        expect {
          post :create, {:ordemservico => valid_attributes}, valid_session
        }.to change(Ordemservico, :count).by(1)
      end

      it "assigns a newly created ordemservico as @ordemservico" do
        post :create, {:ordemservico => valid_attributes}, valid_session
        assigns(:ordemservico).should be_a(Ordemservico)
        assigns(:ordemservico).should be_persisted
      end

      it "redirects to the created ordemservico" do
        post :create, {:ordemservico => valid_attributes}, valid_session
        response.should redirect_to(Ordemservico.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ordemservico as @ordemservico" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ordemservico.any_instance.stub(:save).and_return(false)
        post :create, {:ordemservico => {}}, valid_session
        assigns(:ordemservico).should be_a_new(Ordemservico)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ordemservico.any_instance.stub(:save).and_return(false)
        post :create, {:ordemservico => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ordemservico" do
        ordemservico = Ordemservico.create! valid_attributes
        # Assuming there are no other ordemservicos in the database, this
        # specifies that the Ordemservico created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ordemservico.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ordemservico.to_param, :ordemservico => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ordemservico as @ordemservico" do
        ordemservico = Ordemservico.create! valid_attributes
        put :update, {:id => ordemservico.to_param, :ordemservico => valid_attributes}, valid_session
        assigns(:ordemservico).should eq(ordemservico)
      end

      it "redirects to the ordemservico" do
        ordemservico = Ordemservico.create! valid_attributes
        put :update, {:id => ordemservico.to_param, :ordemservico => valid_attributes}, valid_session
        response.should redirect_to(ordemservico)
      end
    end

    describe "with invalid params" do
      it "assigns the ordemservico as @ordemservico" do
        ordemservico = Ordemservico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ordemservico.any_instance.stub(:save).and_return(false)
        put :update, {:id => ordemservico.to_param, :ordemservico => {}}, valid_session
        assigns(:ordemservico).should eq(ordemservico)
      end

      it "re-renders the 'edit' template" do
        ordemservico = Ordemservico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ordemservico.any_instance.stub(:save).and_return(false)
        put :update, {:id => ordemservico.to_param, :ordemservico => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ordemservico" do
      ordemservico = Ordemservico.create! valid_attributes
      expect {
        delete :destroy, {:id => ordemservico.to_param}, valid_session
      }.to change(Ordemservico, :count).by(-1)
    end

    it "redirects to the ordemservicos list" do
      ordemservico = Ordemservico.create! valid_attributes
      delete :destroy, {:id => ordemservico.to_param}, valid_session
      response.should redirect_to(ordemservicos_url)
    end
  end

end
